# Generated by Django 5.2.17 on 2026-09-16 12:29

import apps.committees.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0001_initial'),
        ('meetings', '0001_initial'),
        ('voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='№ решения')),
                ('text', models.TextField(verbose_name='Текст решения')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
                'ordering': ['item__position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Поручение')),
                ('responsible_name', models.CharField(blank=True, max_length=200, verbose_name='Ответственный (вне системы)')),
                ('due_date', models.DateField(verbose_name='Срок')),
                ('status', models.CharField(choices=[('assigned', 'Назначено'), ('in_progress', 'В работе'), ('on_confirmation', 'На подтверждении'), ('done', 'Исполнено'), ('done_late', 'Исполнено с нарушением срока'), ('cancelled', 'Снято')], default='assigned', max_length=20, verbose_name='Статус')),
                ('reported_at', models.DateTimeField(blank=True, null=True, verbose_name='Отмечено исполнение')),
                ('completed_on', models.DateField(blank=True, null=True, verbose_name='Дата исполнения')),
                ('cancel_reason', models.CharField(blank=True, max_length=300, verbose_name='Причина снятия')),
                ('reminded_7d', models.BooleanField(default=False, editable=False)),
                ('reminded_1d', models.BooleanField(default=False, editable=False)),
                ('overdue_notified', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('co_executors', models.ManyToManyField(blank=True, related_name='co_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Соисполнители')),
                ('commission', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='committees.commission')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='protocols.decision')),
            ],
            options={
                'verbose_name': 'Поручение',
                'verbose_name_plural': 'Поручения',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Комментарий')),
                ('file', models.FileField(blank=True, upload_to=apps.committees.models.upload_path, verbose_name='Файл-подтверждение')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status_change', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='protocols.assignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий к поручению',
                'verbose_name_plural': 'Комментарии к поручениям',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор для проверки')),
                ('kind', models.CharField(choices=[('meeting', 'Протокол заседания'), ('absentee', 'Протокол заочного голосования')], default='meeting', max_length=20, verbose_name='Вид')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Номер')),
                ('protocol_date', models.DateField(verbose_name='Дата')),
                ('place', models.CharField(blank=True, max_length=300, verbose_name='Место')),
                ('format_text', models.CharField(blank=True, max_length=100, verbose_name='Форма проведения')),
                ('preamble', models.TextField(blank=True, verbose_name='Вступительная часть')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approval', 'На согласовании'), ('signing', 'На подписи'), ('signed', 'Подписан'), ('annulled', 'Аннулирован')], default='draft', max_length=20, verbose_name='Статус')),
                ('revision', models.PositiveSmallIntegerField(default=1, verbose_name='Редакция')),
                ('approval_started_at', models.DateTimeField(blank=True, null=True)),
                ('approval_deadline', models.DateField(blank=True, null=True, verbose_name='Срок согласования')),
                ('approval_reminder_sent', models.BooleanField(default=False, editable=False)),
                ('transcription_used', models.BooleanField(default=False, verbose_name='Сформирован с использованием автоматической транскрипции')),
                ('patient_ids_confirmed', models.BooleanField(default=False, verbose_name='Обезличивание подтверждено секретарём')),
                ('snapshot', models.JSONField(blank=True, default=dict, editable=False, verbose_name='Снимок данных на момент подписи')),
                ('frozen_pdf', models.FileField(blank=True, editable=False, upload_to=apps.committees.models.upload_path, verbose_name='PDF на подпись')),
                ('frozen_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 документа на подпись')),
                ('signed_pdf', models.FileField(blank=True, editable=False, upload_to=apps.committees.models.upload_path, verbose_name='Подписанный PDF')),
                ('signed_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='SHA-256 подписанного PDF')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('annulled_reason', models.TextField(blank=True, verbose_name='Причина аннулирования')),
                ('annulled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocols', to='committees.commission')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='protocols', to='meetings.meeting')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='protocols.protocol', verbose_name='Взамен аннулированного')),
                ('votings', models.ManyToManyField(blank=True, related_name='protocols', to='voting.votingsession')),
            ],
            options={
                'verbose_name': 'Протокол',
                'verbose_name_plural': 'Протоколы',
                'ordering': ['-protocol_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='protocols.protocol'),
        ),
        migrations.CreateModel(
            name='ProtocolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='№')),
                ('title', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('patient_id', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ID пациента (МИС)')),
                ('heard', models.TextField(blank=True, verbose_name='Слушали')),
                ('discussed', models.TextField(blank=True, verbose_name='Выступили')),
                ('resolved', models.TextField(blank=True, verbose_name='Решили')),
                ('vote_summary', models.CharField(blank=True, max_length=300, verbose_name='Результаты голосования')),
                ('flagged_names', models.JSONField(blank=True, default=list, verbose_name='Возможные ФИО пациентов (требуют замены на ID)')),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_items', to='meetings.agendaitem')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='protocols.protocol')),
                ('voting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_items', to='voting.votingsession')),
            ],
            options={
                'verbose_name': 'Вопрос протокола',
                'verbose_name_plural': 'Вопросы протокола',
                'ordering': ['protocol', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DissentingOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст особого мнения')),
                ('file', models.FileField(blank=True, upload_to=apps.committees.models.upload_path, verbose_name='Файл')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Подписано')),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('text_hash', models.CharField(blank=True, max_length=64)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dissents', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissents', to='protocols.protocol')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dissents', to='protocols.protocolitem', verbose_name='По вопросу')),
            ],
            options={
                'verbose_name': 'Особое мнение',
                'verbose_name_plural': 'Особые мнения',
                'ordering': ['item__position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='protocols.protocolitem'),
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairman', 'Председатель'), ('deputy', 'Заместитель председателя'), ('secretary', 'Секретарь'), ('member', 'Член комиссии')], max_length=20)),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО подписанта')),
                ('position_text', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время подписи')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('document_hash', models.CharField(max_length=64, verbose_name='Подписанный хэш SHA-256')),
                ('method', models.CharField(default='simple_otp_email', max_length=50, verbose_name='Способ')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=300)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='protocols.protocol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подпись',
                'verbose_name_plural': 'Подписи',
                'ordering': ['signed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProtocolApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Нет ответа'), ('agreed', 'Согласен'), ('remarks', 'Замечания')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, verbose_name='Замечания')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='protocols.protocol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protocol_approvals', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='protocols.protocolitem', verbose_name='К вопросу')),
            ],
            options={
                'verbose_name': 'Согласование протокола',
                'verbose_name_plural': 'Согласования протоколов',
                'unique_together': {('protocol', 'revision', 'user')},
            },
        ),
    ]
