# Generated by Django 5.2.17 on 2026-09-16 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('meeting_scheduled', 'Назначено / перенесено / отменено заседание'), ('meeting_reminder', 'Напоминание о заседании'), ('agenda_approval', 'Повестка на ознакомление'), ('agenda_proposal', 'Предложения в повестку'), ('materials_added', 'Добавлены материалы'), ('protocol_approval', 'Проект протокола на согласование'), ('protocol_signing', 'Протокол на подпись'), ('protocol_signed', 'Протокол подписан'), ('voting', 'Голосование: открыто / напоминание / итоги'), ('assignment', 'Поручения: назначение / напоминание / просрочка'), ('legal_act', 'НПА утратил силу или недоступен'), ('regulation_review', 'Плановый пересмотр положения'), ('composition', 'Изменения состава и приказы'), ('system', 'Системные сообщения')], max_length=40, verbose_name='Событие')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, verbose_name='Текст')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='committees.commission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('meeting_scheduled', 'Назначено / перенесено / отменено заседание'), ('meeting_reminder', 'Напоминание о заседании'), ('agenda_approval', 'Повестка на ознакомление'), ('agenda_proposal', 'Предложения в повестку'), ('materials_added', 'Добавлены материалы'), ('protocol_approval', 'Проект протокола на согласование'), ('protocol_signing', 'Протокол на подпись'), ('protocol_signed', 'Протокол подписан'), ('voting', 'Голосование: открыто / напоминание / итоги'), ('assignment', 'Поручения: назначение / напоминание / просрочка'), ('legal_act', 'НПА утратил силу или недоступен'), ('regulation_review', 'Плановый пересмотр положения'), ('composition', 'Изменения состава и приказы'), ('system', 'Системные сообщения')], max_length=40)),
                ('email', models.BooleanField(default=True, verbose_name='E-mail')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройка уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
