# Generated by Django 5.2.17 on 2026-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Задача')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('last_result', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Запуск периодической задачи',
                'verbose_name_plural': 'Запуски периодических задач',
            },
        ),
    ]
