# Generated by Django 5.2.17 on 2026-09-16 12:29

import apps.committees.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0001_initial'),
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение / проект решения')),
                ('deadline', models.DateTimeField(verbose_name='Окончание голосования')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Разрешить комментарий')),
                ('status', models.CharField(choices=[('draft', 'Подготовка'), ('open', 'Идёт голосование'), ('closed', 'Завершено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('adopted', 'Решение принято'), ('rejected', 'Решение не принято'), ('no_quorum', 'Кворум не набран')], max_length=20, verbose_name='Итог')),
                ('votes_for', models.PositiveSmallIntegerField(default=0)),
                ('votes_against', models.PositiveSmallIntegerField(default=0)),
                ('votes_abstain', models.PositiveSmallIntegerField(default=0)),
                ('quorum_needed', models.PositiveSmallIntegerField(default=0)),
                ('reminder_sent', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='meetings.agendaitem')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='committees.commission')),
                ('eligible', models.ManyToManyField(blank=True, editable=False, related_name='eligible_votings', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Голосование',
                'verbose_name_plural': 'Голосования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VotingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('file', models.FileField(blank=True, upload_to=apps.committees.models.upload_path)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='voting.votingsession')),
            ],
            options={
                'verbose_name': 'Материал голосования',
                'verbose_name_plural': 'Материалы голосования',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('for', 'За'), ('against', 'Против'), ('abstain', 'Воздержался')], max_length=10, verbose_name='Голос')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cast_at', models.DateTimeField(auto_now=True, verbose_name='Время голоса')),
                ('entered_by', models.ForeignKey(blank=True, help_text='Заполнено, если голос внесён секретарём со слов члена комиссии.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='voting.votingsession')),
            ],
            options={
                'verbose_name': 'Голос',
                'verbose_name_plural': 'Голоса',
                'unique_together': {('session', 'user')},
            },
        ),
    ]
