# Generated by Django 5.2.17 on 2026-09-16 12:29

import apps.committees.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('committees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('description', models.TextField(blank=True, verbose_name='Обоснование')),
                ('speaker_name', models.CharField(blank=True, max_length=200, verbose_name='Предлагаемый докладчик')),
                ('patient_id', models.CharField(blank=True, max_length=40, verbose_name='ID пациента (МИС)')),
                ('requires_vote', models.BooleanField(default=False, verbose_name='Требуется голосование')),
                ('file', models.FileField(blank=True, upload_to=apps.committees.models.upload_path, verbose_name='Материал')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'На рассмотрении'), ('accepted', 'Включён в повестку'), ('rejected', 'Отклонён')], default='new', max_length=20, verbose_name='Статус')),
                ('response', models.CharField(blank=True, max_length=500, verbose_name='Ответ секретаря')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agenda_proposals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Предложение в повестку',
                'verbose_name_plural': 'Предложения в повестку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1, verbose_name='№')),
                ('title', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение')),
                ('speaker_name', models.CharField(blank=True, max_length=200, verbose_name='Докладчик (не пользователь системы)')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=10, verbose_name='Регламент, мин')),
                ('patient_id', models.CharField(blank=True, db_index=True, help_text='Только внутренний идентификатор пациента из МИС — без ФИО, ИИН и даты рождения.', max_length=40, verbose_name='ID пациента (МИС)')),
                ('requires_vote', models.BooleanField(default=False, verbose_name='Выносится на голосование')),
                ('is_control_item', models.BooleanField(default=False, editable=False, verbose_name='Контроль исполнения решений')),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='committees.rubric', verbose_name='Рубрика')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Докладчик')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meetings.agendaproposal')),
            ],
            options={
                'verbose_name': 'Вопрос повестки',
                'verbose_name_plural': 'Повестка',
                'ordering': ['meeting', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('planned', 'Плановое'), ('extra', 'Внеочередное')], default='planned', max_length=20, verbose_name='Тип')),
                ('starts_at', models.DateTimeField(verbose_name='Дата и время')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=90, verbose_name='Длительность, мин')),
                ('format', models.CharField(choices=[('offline', 'Очное'), ('online', 'Онлайн'), ('mixed', 'Смешанное')], default='offline', max_length=20, verbose_name='Формат')),
                ('place', models.CharField(blank=True, max_length=300, verbose_name='Место')),
                ('video_link', models.URLField(blank=True, verbose_name='Ссылка на видеоконференцию')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('held', 'Проведено'), ('postponed', 'Перенесено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус')),
                ('original_starts_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Исходная дата')),
                ('cancel_reason', models.CharField(blank=True, max_length=300, verbose_name='Причина отмены')),
                ('agenda_status', models.CharField(choices=[('draft', 'Формируется'), ('approved', 'Утверждена председателем')], default='draft', max_length=20, verbose_name='Повестка')),
                ('agenda_approved_at', models.DateTimeField(blank=True, null=True)),
                ('proposals_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Приём предложений в повестку до')),
                ('reminder_3d_sent', models.BooleanField(default=False, editable=False)),
                ('reminder_1d_sent', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cities', models.ManyToManyField(blank=True, to='accounts.city', verbose_name='Площадки-участники')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='committees.commission')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заседание',
                'verbose_name_plural': 'Заседания',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'Файл'), ('link', 'Ссылка'), ('audio', 'Аудиозапись (ссылка)'), ('video', 'Видеозапись (ссылка)')], default='file', max_length=10, verbose_name='Вид')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('file', models.FileField(blank=True, upload_to=apps.committees.models.upload_path, verbose_name='Файл')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='meetings.agendaitem', verbose_name='Вопрос повестки')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Материал заседания',
                'verbose_name_plural': 'Материалы заседаний',
                'ordering': ['agenda_item__position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='agendaproposal',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='meetings.meeting'),
        ),
        migrations.CreateModel(
            name='MeetingReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_starts_at', models.DateTimeField(verbose_name='Было')),
                ('new_starts_at', models.DateTimeField(verbose_name='Стало')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='Причина')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Перенос заседания',
                'verbose_name_plural': 'Переносы заседаний',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Распознаётся'), ('done', 'Готов'), ('failed', 'Ошибка'), ('manual', 'Внесён вручную')], default='pending', max_length=20)),
                ('text', models.TextField(blank=True, verbose_name='Текст с таймкодами')),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.material', verbose_name='Аудиозапись')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Транскрипт',
                'verbose_name_plural': 'Транскрипты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField(verbose_name='Доступ до')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашённые участники',
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Присутствовал очно'), ('online', 'Присутствовал онлайн'), ('absent_excused', 'Отсутствовал по уважительной причине'), ('absent', 'Отсутствовал')], max_length=20, verbose_name='Отметка')),
                ('is_invited', models.BooleanField(default=False, verbose_name='Приглашённый')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='committees.absencereason', verbose_name='Причина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Отметка присутствия',
                'verbose_name_plural': 'Список присутствующих',
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AgendaAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ack', 'Ознакомлен'), ('suggestion', 'Предложение по повестке')], max_length=20)),
                ('text', models.TextField(blank=True, verbose_name='Предложение')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='meetings.meeting')),
            ],
            options={
                'verbose_name': 'Ознакомление с повесткой',
                'verbose_name_plural': 'Ознакомление с повесткой',
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
