# Generated by Django 5.2.17 on 2026-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='agenda_status',
            field=models.CharField(choices=[('draft', 'Формируется'), ('submitted', 'На утверждении у председателя'), ('approved', 'Утверждена председателем')], default='draft', max_length=20, verbose_name='Повестка'),
        ),
    ]
