# Generated by Django 5.2.17 on 2026-09-16 12:29

import apps.committees.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Причина')),
                ('is_excused', models.BooleanField(default=True, verbose_name='Уважительная')),
            ],
            options={
                'verbose_name': 'Причина отсутствия',
                'verbose_name_plural': 'Причины отсутствия',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Наименование')),
                ('is_working_day', models.BooleanField(default=False, help_text='Отметьте, если выходной день перенесён и является рабочим.', verbose_name='Рабочий день (перенос)')),
            ],
            options={
                'verbose_name': 'День производственного календаря',
                'verbose_name_plural': 'Производственный календарь',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Краткое наименование')),
                ('kind', models.CharField(choices=[('core', 'Основная (на старте)'), ('required_if', 'Требуется НПА при наличии деятельности'), ('recommended', 'Создаётся приказом руководителя')], default='core', max_length=20, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Назначение')),
                ('established_on', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('handles_patient_cases', models.BooleanField(default=False, help_text='В вопросах повестки указывается только внутренний ID пациента из МИС.', verbose_name='Рассматривает клинические случаи')),
                ('meeting_quorum_numerator', models.PositiveSmallIntegerField(default=1, verbose_name='Кворум заседания: числитель')),
                ('meeting_quorum_denominator', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кворум заседания: знаменатель')),
                ('meeting_quorum_strict', models.BooleanField(default=True, help_text='Включено — «более половины»; выключено — «не менее».', verbose_name='Кворум заседания: строго больше доли')),
                ('vote_quorum_numerator', models.PositiveSmallIntegerField(default=2, verbose_name='Кворум голосования: числитель')),
                ('vote_quorum_denominator', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кворум голосования: знаменатель')),
                ('approval_days', models.PositiveSmallIntegerField(default=3, verbose_name='Срок согласования протокола, рабочих дней')),
                ('vote_days', models.PositiveSmallIntegerField(default=3, verbose_name='Срок голосования по умолчанию, рабочих дней')),
                ('open_voting', models.BooleanField(default=True, verbose_name='Поимённые результаты голосования видны членам')),
                ('allow_vote_change', models.BooleanField(default=True, verbose_name='Разрешено менять голос до окончания срока')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='Уведомления в WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cities', models.ManyToManyField(blank=True, to='accounts.city', verbose_name='Площадки')),
            ],
            options={
                'verbose_name': 'Комиссия',
                'verbose_name_plural': 'Комиссии',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order', 'Приказ о составе'), ('agenda', 'Повестка'), ('protocol', 'Протокол заседания'), ('absentee_protocol', 'Протокол заочного голосования'), ('report', 'Отчёт')], max_length=30, verbose_name='Вид')),
                ('file', models.FileField(upload_to=apps.committees.models.upload_path, verbose_name='Файл DOCX')),
                ('is_active', models.BooleanField(default=True, verbose_name='Используется')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(blank=True, help_text='Пусто — шаблон по умолчанию для всех комиссий.', null=True, on_delete=django.db.models.deletion.CASCADE, to='committees.commission', verbose_name='Комиссия')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.CreateModel(
            name='LegalAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер')),
                ('act_date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('authority', models.CharField(blank=True, default='МЗ РК', max_length=200, verbose_name='Орган')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на adilet.zan.kz')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
                ('status', models.CharField(choices=[('actual', 'Актуален'), ('lost_force', 'Утратил силу'), ('unavailable', 'Недоступен'), ('needs_check', 'Требует проверки'), ('retired', 'Утратил силу, замена не требуется')], default='needs_check', max_length=20, verbose_name='Статус')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acts', to='committees.commission')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='committees.legalact', verbose_name='Заменён на')),
            ],
            options={
                'verbose_name': 'НПА',
                'verbose_name_plural': 'Нормативная база',
                'ordering': ['commission', 'sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalActCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата проверки')),
                ('url', models.URLField(blank=True, max_length=500)),
                ('result', models.CharField(choices=[('actual', 'Актуален'), ('lost_force', 'Утратил силу'), ('unavailable', 'Недоступен'), ('needs_check', 'Требует проверки'), ('retired', 'Утратил силу, замена не требуется')], max_length=20, verbose_name='Результат')),
                ('details', models.TextField(blank=True, verbose_name='Подробности')),
                ('manual', models.BooleanField(default=False, verbose_name='Внеплановая')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='committees.legalact')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проверка НПА',
                'verbose_name_plural': 'Журнал проверок НПА',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О составе комиссии', max_length=300, verbose_name='Заголовок')),
                ('preamble', models.TextField(blank=True, verbose_name='Преамбула')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Номер')),
                ('signed_on', models.DateField(blank=True, null=True, verbose_name='Дата подписания')),
                ('status', models.CharField(choices=[('draft', 'Проект'), ('signed', 'Подписан'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('draft_file', models.FileField(blank=True, upload_to=apps.committees.models.upload_path, verbose_name='Проект (DOCX)')),
                ('scan_file', models.FileField(blank=True, upload_to=apps.committees.models.upload_path, verbose_name='Скан подписанного приказа (PDF)')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='committees.commission')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
                'ordering': ['-signed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chairman', 'Председатель'), ('deputy', 'Заместитель председателя'), ('secretary', 'Секретарь'), ('member', 'Член комиссии')], max_length=20, verbose_name='Роль')),
                ('role_order', models.PositiveSmallIntegerField(default=2, editable=False)),
                ('position_text', models.CharField(blank=True, max_length=200, verbose_name='Должность (на момент включения)')),
                ('city_text', models.CharField(blank=True, max_length=100, verbose_name='Город (на момент включения)')),
                ('start_date', models.DateField(verbose_name='Входит в состав с')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Выведен из состава с')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_records', to='committees.commission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_records', to=settings.AUTH_USER_MODEL)),
                ('end_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_records', to='committees.order')),
                ('start_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_records', to='committees.order')),
            ],
            options={
                'verbose_name': 'Период членства',
                'verbose_name_plural': 'История состава',
                'ordering': ['commission', 'role_order', 'user__last_name', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompositionChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Ввести в состав'), ('remove', 'Вывести из состава'), ('change_role', 'Изменить роль'), ('update_position', 'Изменить должность')], max_length=20, verbose_name='Изменение')),
                ('new_role', models.CharField(blank=True, choices=[('chairman', 'Председатель'), ('deputy', 'Заместитель председателя'), ('secretary', 'Секретарь'), ('member', 'Член комиссии')], max_length=20, verbose_name='Роль')),
                ('new_position', models.CharField(blank=True, max_length=200, verbose_name='Новая должность')),
                ('basis', models.CharField(blank=True, max_length=300, verbose_name='Основание')),
                ('status', models.CharField(choices=[('project', 'Проект состава'), ('applied', 'Действует'), ('cancelled', 'Отменено')], default='project', max_length=20, verbose_name='Статус')),
                ('applied_on', models.DateField(blank=True, null=True, verbose_name='Вступило в силу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition_changes', to='committees.commission')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='committees.order', verbose_name='Приказ')),
            ],
            options={
                'verbose_name': 'Изменение состава',
                'verbose_name_plural': 'Изменения состава',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='committees.commission')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observed_commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Доступ наблюдателя',
                'verbose_name_plural': 'Доступы наблюдателей',
                'unique_together': {('commission', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Редакция')),
                ('title', models.CharField(default='Положение о комиссии', max_length=300, verbose_name='Наименование')),
                ('approved_on', models.DateField(verbose_name='Дата утверждения')),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='Номер утверждающего приказа')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата утверждающего приказа')),
                ('file', models.FileField(upload_to=apps.committees.models.upload_path, verbose_name='Файл (PDF/DOCX)')),
                ('review_on', models.DateField(blank=True, null=True, verbose_name='Дата планового пересмотра')),
                ('expired_on', models.DateField(blank=True, null=True, verbose_name='Утратила силу с')),
                ('review_reminder_sent', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulations', to='committees.commission')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Положение о комиссии',
                'verbose_name_plural': 'Положения о комиссиях',
                'ordering': ['commission', '-version'],
                'unique_together': {('commission', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Рубрика')),
                ('sort', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='committees.commission')),
            ],
            options={
                'verbose_name': 'Рубрика вопросов',
                'verbose_name_plural': 'Рубрикатор вопросов',
                'ordering': ['commission', 'sort', 'name'],
                'unique_together': {('commission', 'name')},
            },
        ),
    ]
