# Generated by Django 5.2.17 on 2026-09-16 12:29

import apps.committees.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('committees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('period_start', models.DateField(verbose_name='Период с')),
                ('period_end', models.DateField(verbose_name='Период по')),
                ('pdf', models.FileField(upload_to=apps.committees.models.upload_path)),
                ('document_hash', models.CharField(max_length=64)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='signed_reports', to='committees.commission')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписанный отчёт',
                'verbose_name_plural': 'Подписанные отчёты',
                'ordering': ['-signed_at'],
            },
        ),
    ]
